In [1]:
import numpy as np

In [2]:
#We will use np.save and np.load for saving arrays and loading arrays to and from disk!

In [3]:
#files are stores as .npy in disk.

In [4]:
arr=np.arange(5,51,5).reshape(5,2)

In [5]:
arr1=np.linspace(6,60,10).reshape(5,2)

In [6]:
arr

array([[ 5, 10],
       [15, 20],
       [25, 30],
       [35, 40],
       [45, 50]])

In [7]:
arr1

array([[ 6., 12.],
       [18., 24.],
       [30., 36.],
       [42., 48.],
       [54., 60.]])

In [8]:
np.save('5_table',arr)

In [9]:
np.savez('5&6_table',a=arr,b=arr1)       #To save multiple files np.savez is used and multiple files are passed by keyworded args

In [10]:
np.load('5_table.npy')

array([[ 5, 10],
       [15, 20],
       [25, 30],
       [35, 40],
       [45, 50]])

In [11]:
dic=np.load('5&6_table.npz')             #a dict-like object is returned. To access it, key is used which we used in saving it!

In [13]:
dic['b']

array([[ 6., 12.],
       [18., 24.],
       [30., 36.],
       [42., 48.],
       [54., 60.]])