In [1]:
from numpy.linalg import inv

In [2]:
import numpy as np

In [3]:
A=np.array([34,3,4,4,6,88,87,66,98]).reshape(3,3)

In [4]:
A

array([[34,  3,  4],
       [ 4,  6, 88],
       [87, 66, 98]])

In [5]:
B=np.dot(A,A.T)

In [6]:
B

array([[ 1181,   506,  3548],
       [  506,  7796,  9368],
       [ 3548,  9368, 21529]])

In [7]:
np.dot(B,inv(B))

array([[ 1.00000000e+00, -7.15573434e-18,  2.50884383e-16],
       [-6.11490025e-16,  1.00000000e+00,  4.82686807e-16],
       [-1.67606814e-15,  5.16134444e-16,  1.00000000e+00]])

In [8]:
#Above matrix is identity matrix.This inverse was really calculated>

In [9]:
#Pg. no: 117