In [1]:
import numpy as np

In [2]:
a=['2','3','65']

In [3]:
arr=np.array(a)

In [4]:
arr

array(['2', '3', '65'], dtype='<U2')

In [5]:
#Now, How to change data types???
#Thats where astype() comes to rescue.

In [7]:
arr.astype(np.int32)

array([ 2,  3, 65])

In [8]:
arr.astype(np.float32)

array([ 2.,  3., 65.], dtype=float32)

In [9]:
#WE CAN EXPLICITLY PROVIDE DTYPE DURING INITIALIZATION

In [14]:
np.array([2,3,4,5,6],dtype='float64')

array([2., 3., 4., 5., 6.])