In [1]:
import numpy as np

In [8]:
a=np.array([[1,2,3],[4,6,5],[4,2,4]])

In [9]:
a

array([[1, 2, 3],
       [4, 6, 5],
       [4, 2, 4]])

In [10]:
b=a.T

In [11]:
b

array([[1, 4, 4],
       [2, 6, 2],
       [3, 5, 4]])

In [12]:
a+b

array([[ 2,  6,  7],
       [ 6, 12,  7],
       [ 7,  7,  8]])

In [13]:
a-b

array([[ 0, -2, -1],
       [ 2,  0,  3],
       [ 1, -3,  0]])

In [14]:
a*b

array([[ 1,  8, 12],
       [ 8, 36, 10],
       [12, 10, 16]])

In [15]:
a/b

array([[1.        , 0.5       , 0.75      ],
       [2.        , 1.        , 2.5       ],
       [1.33333333, 0.4       , 1.        ]])

In [16]:
a//b

array([[1, 0, 0],
       [2, 1, 2],
       [1, 0, 1]], dtype=int32)

In [17]:
5+a

array([[ 6,  7,  8],
       [ 9, 11, 10],
       [ 9,  7,  9]])

In [18]:
5*b

array([[ 5, 20, 20],
       [10, 30, 10],
       [15, 25, 20]])

In [19]:
#Comparison of arrays of same shape produce boolean array

In [20]:
a>b

array([[False, False, False],
       [ True, False,  True],
       [ True, False, False]])