In [1]:
import numpy as np

In [2]:
#Look,the major difference b/w list and ndarray is memory optimization. Slicing produces views. Any changes incorporated
#to view will be reflected on original ndarray!!!
#slice.copy() creates copy

In [3]:
arr=np.array([1,2,3,4,5])

In [4]:
arr[0]

1

In [5]:
arr[-1]

5

In [6]:
slice1=arr[1:4]

In [7]:
slice1

array([2, 3, 4])

In [8]:
slice1[0]=45

In [9]:
arr

array([ 1, 45,  3,  4,  5])

In [10]:
slice_copy=arr[3:].copy()
slice_copy

array([4, 5])

In [11]:
slice_copy[0]=8888

In [12]:
arr

array([ 1, 45,  3,  4,  5])

In [13]:
arr2=np.array([[1,2,3,],[4,5,6],[7,8,9]])

In [14]:
arr2[0,2]

3

In [15]:
#Slicing in 3X3 ndarray:

In [16]:
arr3=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [17]:
arr3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
#Axis Concept: Axis 0 is along direction of rows and Axis 1 is along direction of columns

In [19]:
arr3[:2,0]               #rows:0,1 columns:0

array([1, 4])

In [20]:
arr3[:2,:]              #rows:0,1 columns=0,1,2 (all)

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
#Boolean Indexing:
#Instead of passing intergers, as row and column nos, true or false will determine which row or column to choose.

In [22]:
names=np.array(['anuj','lokesh','aman'])

In [23]:
names=='anuj' #This is a bo0lean array. We can pass it to array as a slice!

array([ True, False, False])

In [24]:
arr3[names=='anuj']

array([[1, 2, 3]])

In [25]:
arr3[names=='anuj',1:]

array([[2, 3]])

In [26]:
#NOTE: len(names)=no. of rows in ndarray!!!

In [27]:
arr3[names=='anuj',1:]=55

In [28]:
arr3

array([[ 1, 55, 55],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [29]:
#Fancy Indexing: Directly getting what we want!

In [30]:
arr=np.arange(30).reshape((10,3))

In [31]:
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])

In [32]:
arr[[0,-1,5,6]]                     #Direct give indices in form of list

array([[ 0,  1,  2],
       [27, 28, 29],
       [15, 16, 17],
       [18, 19, 20]])

In [33]:
arr[[0,-1,5,6],[0,0,0,0]]          #Point to note these are copies not views!

array([ 0, 27, 15, 18])

In [34]:
arr[1:-1,0]                       #This is our normal slicing. Views are generated!

array([ 3,  6,  9, 12, 15, 18, 21, 24])

In [35]:
#Transposing and Swapping axes:

In [36]:
arr=np.arange(12).reshape((3,4))

In [37]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [38]:
arr=arr.T

In [39]:
arr

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [40]:
#Transpose,Swapaxes functions are too there. We will skip them for now.

In [41]:
#Python for data science by O'Reilly pg no:103