In [1]:
import numpy as np

In [2]:
#Universal functions are nothing but functions that does element-wise transformations.
#It is termed unary or binary depending upon number of arrays it can take(1 or 2)

In [3]:
#Unary Functions

In [4]:
arr=np.array([1,4,9,16,25,36,49,64,81,100],dtype='float64')

In [5]:
np.sqrt(arr)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [6]:
arr

array([  1.,   4.,   9.,  16.,  25.,  36.,  49.,  64.,  81., 100.])

In [7]:
np.sqrt(arr,arr)                    #Passing same array as 2nd argument executes inplace operation

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [8]:
arr

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [9]:
np.exp(arr)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04])

In [10]:
np.square(np.sqrt(arr))

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [11]:
#There are other universal binary functions as well

In [12]:
#Binary functions:

In [13]:
arr1=np.arange(10)

In [14]:
np.maximum(arr,arr1)                   #Picks out maximum element-wise

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [15]:
#Some unary functions return two arrays!

In [16]:
arr2=np.random.rand(10)*6

In [17]:
arr2

array([4.08484325, 3.22816836, 2.4076328 , 0.29007325, 2.54949673,
       0.97264773, 2.52664076, 2.61527669, 4.4227711 , 2.01966613])

In [18]:
r,whole=np.modf(arr2)

In [19]:
r

array([0.08484325, 0.22816836, 0.4076328 , 0.29007325, 0.54949673,
       0.97264773, 0.52664076, 0.61527669, 0.4227711 , 0.01966613])

In [20]:
whole

array([4., 3., 2., 0., 2., 0., 2., 2., 4., 2.])

In [21]:
#Many more functions are there.
#Python for data science by O'Reilly: Pg no:107