In [1]:
import numpy as np

In [2]:
#Universal functions are nothing but functions that does element-wise transformations.
#It is termed unary or binary depending upon number of arrays it can take(1 or 2)

In [3]:
#Unary Functions

In [4]:
arr=np.array([1,4,9,16,25,36,49,64,81,100])

In [5]:
np.sqrt(arr)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [6]:
np.exp(arr)

array([2.71828183e+00, 5.45981500e+01, 8.10308393e+03, 8.88611052e+06,
       7.20048993e+10, 4.31123155e+15, 1.90734657e+21, 6.23514908e+27,
       1.50609731e+35, 2.68811714e+43])

In [7]:
np.square(np.sqrt(arr))

array([  1.,   4.,   9.,  16.,  25.,  36.,  49.,  64.,  81., 100.])

In [8]:
#There are other universal binary functions as well

In [9]:
#Binary functions:

In [10]:
arr1=np.arange(10)

In [11]:
np.maximum(arr,arr1)                   #Picks out maximum element-wise

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [12]:
#Some unary functions return two arrays!

In [13]:
arr2=np.random.rand(10)*6

In [14]:
arr2

array([3.53927353, 3.26592301, 0.04031967, 2.77308078, 5.47794293,
       2.0123236 , 3.92547832, 4.85974303, 4.11657633, 2.62397069])

In [15]:
r,whole=np.modf(arr2)

In [16]:
r

array([0.53927353, 0.26592301, 0.04031967, 0.77308078, 0.47794293,
       0.0123236 , 0.92547832, 0.85974303, 0.11657633, 0.62397069])

In [17]:
whole

array([3., 3., 0., 2., 5., 2., 3., 4., 4., 2.])

In [18]:
#Many more functions are there.
#Python for data science by O'Reilly: Pg no:107