In [1]:
import numpy as np

In [2]:
arr=np.random.randn(5,3)

In [3]:
arr

array([[ 0.83394239, -0.16650263,  0.86239354],
       [ 0.80269087, -0.13227959,  1.16831354],
       [-0.0442129 , -0.59483129,  1.38889438],
       [-0.19388493,  0.19541783, -0.03973434],
       [-1.35607538, -0.73811625, -0.52829199]])

In [4]:
arr>1

array([[False, False, False],
       [False, False,  True],
       [False, False,  True],
       [False, False, False],
       [False, False, False]])

In [5]:
np.where(arr>1,2,0)  #3 args: 1st:condition 2nd:in return array, true positions are replaced by that of this arg. 3rd:in return array, false positions are replaced by that of this arg.

array([[0, 0, 0],
       [0, 0, 2],
       [0, 0, 2],
       [0, 0, 0],
       [0, 0, 0]])

In [6]:
np.where(arr>1,2,arr)                 #This means if condition is false, do nothing

array([[ 0.83394239, -0.16650263,  0.86239354],
       [ 0.80269087, -0.13227959,  2.        ],
       [-0.0442129 , -0.59483129,  2.        ],
       [-0.19388493,  0.19541783, -0.03973434],
       [-1.35607538, -0.73811625, -0.52829199]])