In [1]:
import numpy as np

In [2]:
#We are going to use methods associated with array instance since they give more facilities in terms of axes.

In [3]:
arr=np.random.randn(6,3)

In [4]:
arr

array([[-0.45810789, -0.25778092, -1.50292862],
       [-0.07721618, -1.13670271, -1.61141769],
       [ 0.01877981,  0.57456664, -1.80349781],
       [ 0.48429586,  0.39238943, -0.88521249],
       [ 0.98924458, -0.65151447, -0.43476485],
       [-0.22926843,  0.8599829 , -1.26757163]])

In [5]:
arr.sum()

-6.996724489936682

In [6]:
arr.sum(axis=1)

array([-2.21881743, -2.82533658, -1.21015137, -0.00852721, -0.09703474,
       -0.63685716])

In [7]:
arr.mean(axis=0)

array([ 0.12128796, -0.03650986, -1.25089885])

In [10]:
arr.std()

0.8318761015459861

In [11]:
arr.cumsum(axis=1)                     #Cumulative sum across columns (More like fabonacci series)

array([[-0.45810789, -0.71588881, -2.21881743],
       [-0.07721618, -1.21391889, -2.82533658],
       [ 0.01877981,  0.59334644, -1.21015137],
       [ 0.48429586,  0.87668529, -0.00852721],
       [ 0.98924458,  0.33773011, -0.09703474],
       [-0.22926843,  0.63071447, -0.63685716]])

In [13]:
arr.cumprod(axis=0)                     #Cumulative product across rows

array([[-4.58107889e-01, -2.57780920e-01, -1.50292862e+00],
       [ 3.53733420e-02,  2.93020270e-01,  2.42184577e+00],
       [ 6.64304478e-04,  1.68359672e-01, -4.36779355e+00],
       [ 3.21719909e-04,  6.60625549e-02,  3.86642541e+00],
       [ 3.18259677e-04, -4.30407107e-02, -1.68098587e+00],
       [-7.29668955e-05, -3.70142750e-02,  2.13077000e+00]])