In [1]:
import numpy as np

In [2]:
arr=np.random.randn(6,3)

In [3]:
arr

array([[-1.28736193,  0.08161384, -0.46511681],
       [ 1.71777945, -0.68227455, -0.50869466],
       [-0.82484071,  0.09842058, -0.46911929],
       [ 0.68689209, -1.18993227,  0.77157966],
       [-1.84166397,  0.6464311 ,  1.23825675],
       [ 2.31556692, -0.09519048, -0.27049684]])

In [4]:
arr.sort()            #sorting in-place operation dafault axis is 1

In [5]:
arr

array([[-1.28736193, -0.46511681,  0.08161384],
       [-0.68227455, -0.50869466,  1.71777945],
       [-0.82484071, -0.46911929,  0.09842058],
       [-1.18993227,  0.68689209,  0.77157966],
       [-1.84166397,  0.6464311 ,  1.23825675],
       [-0.27049684, -0.09519048,  2.31556692]])

In [6]:
arr.sort(axis=0)

In [7]:
arr

array([[-1.84166397, -0.50869466,  0.08161384],
       [-1.28736193, -0.46911929,  0.09842058],
       [-1.18993227, -0.46511681,  0.77157966],
       [-0.82484071, -0.09519048,  1.23825675],
       [-0.68227455,  0.6464311 ,  1.71777945],
       [-0.27049684,  0.68689209,  2.31556692]])

In [8]:
#Python set logic can also be applied on ndarrays: These are top level numpy functions

In [9]:
arr1=np.array(['reena','bob','anuj','bob','anuj','reena'])

In [10]:
np.unique(arr1)

array(['anuj', 'bob', 'reena'], dtype='<U5')

In [11]:
arr2=np.array([5,3,4,5,4,3,5,4,3,3,4,5,5,4,4])

In [12]:
arr3=np.array([1,3,2,4,3,5,3])

In [13]:
np.intersect1d(arr2,arr3)

array([3, 4, 5])

In [14]:
np.union1d(arr2,arr3)

array([1, 2, 3, 4, 5])

In [15]:
#For other set-like operations : look pg no:115