In [1]:
import numpy as np

# |How to create ndarrays?

In [2]:
arr=np.array([1,2,3],dtype='float64') #it accepts sequences,bools too

In [3]:
np.zeros(4)        #it accepts shape:(3,3,4)

array([0., 0., 0., 0.])

In [4]:
#np.zeros_like(),np.ones(),np.ones_like(),full,full_like,empty,empty_like,eye,identity,arange,linspace

# How to typecast arrays?

In [5]:
arr.astype(np.int64)

array([1, 2, 3], dtype=int64)

# How to perform arithmetic operations?

In [6]:
a=np.arange(5)
b=np.arange(6,11)

In [7]:
a+b

array([ 6,  8, 10, 12, 14])

In [8]:
1/a

c:\users\anujs\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ])

# How to index and slice?

In [9]:
a

array([0, 1, 2, 3, 4])

In [10]:
a[4]

4

In [11]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [12]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
arr[:2,:]

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
arr[:2,2]

array([3, 6])

In [15]:
arr[arr>5]

array([6, 7, 8, 9])

In [16]:
arr[[1,2]]

array([[4, 5, 6],
       [7, 8, 9]])

# Remember universal functions?

In [17]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
b=np.sqrt(arr)

In [19]:
r,w=np.modf(b)

In [20]:
r

array([[0.        , 0.41421356, 0.73205081],
       [0.        , 0.23606798, 0.44948974],
       [0.64575131, 0.82842712, 0.        ]])

In [21]:
w

array([[1., 1., 1.],
       [2., 2., 2.],
       [2., 2., 3.]])

# NP.WHERE?

In [22]:
np.where(arr>5,0,arr)

array([[1, 2, 3],
       [4, 5, 0],
       [0, 0, 0]])

In [23]:
arr.sum()

45

In [24]:
arr.mean(axis=0)

array([4., 5., 6.])

In [25]:
# arr.std(),arr.cumsum(),arr.cumprod()

# Operations on boolean arrays?

In [26]:
arr>3

array([[False, False, False],
       [ True,  True,  True],
       [ True,  True,  True]])

In [27]:
(arr>3).sum()

6

In [28]:
#b_arr.any(),b_arr.all()

# Sorting and Set-Logic?

In [29]:
a=np.array([[34,1,33],[2,4,67],[90,12,2]])

In [30]:
a

array([[34,  1, 33],
       [ 2,  4, 67],
       [90, 12,  2]])

In [31]:
np.sort(a)

array([[ 1, 33, 34],
       [ 2,  4, 67],
       [ 2, 12, 90]])

In [32]:
a

array([[34,  1, 33],
       [ 2,  4, 67],
       [90, 12,  2]])

In [33]:
a.sort(axis=0)

In [34]:
a

array([[ 2,  1,  2],
       [34,  4, 33],
       [90, 12, 67]])

In [35]:
np.unique(a)

array([ 1,  2,  4, 12, 33, 34, 67, 90])

In [36]:
a

array([[ 2,  1,  2],
       [34,  4, 33],
       [90, 12, 67]])

In [37]:
b=a[1:,1:]

In [38]:
np.intersect1d(a,b)

array([ 4, 12, 33, 67])

# np.save ,np.savez ,np.load???

In [39]:
#np.save('npy_file_name',array)

In [40]:
#np.savez('npz_file_name',array1=arr1,array2=arr2....)

In [41]:
#np.load('npy_file_name.npy')

In [42]:
##dic=np.load('npy_file_name.npz')
#dic['array1'] to access 1st array

# Linear Algebra ??

In [43]:
from numpy.linalg import inv

In [44]:
A=np.array([[1,4,23],[5,76,5],[9,7,5]])

In [45]:
np.dot(A,inv(A))

array([[1.00000000e+00, 2.16840434e-18, 3.64291930e-17],
       [2.08166817e-17, 1.00000000e+00, 8.84708973e-17],
       [2.08166817e-17, 3.03576608e-18, 1.00000000e+00]])

In [46]:
#Thats a identity matrix